events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/auth {
            proxy_pass http://auth-service:8000;
        }

        location /api/catalog {
            proxy_pass http://catalog-service:4000;
        }

        location /api/orders {
            proxy_pass http://orders-service:8001;
        }

        location /healthz {
            proxy_pass http://orders-service:8001/healthz;
        }

        # Fallback for the static frontend index.html page
        location / {
            proxy_pass http://frontend:80;
        }
    }
}
