permissions:
  id-token: write
  contents: read

- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: ${{ secrets.ARN_TO_ASSUME1 }}
    role-session-name: GitHub_to_AWS_via_FederatedOIDC
    aws-region: ${{ secrets.AWS_REGION1 }}

- name: Verify AWS Identity
  run: aws sts get-caller-identity